name: our_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  provider: ^6.1.2
  http: ^1.2.1
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    

  fonts:  
    - family: My1
      fonts:
        - asset: assets/fonts/1.ttf
    - family: My2
      fonts:
        - asset: assets/fonts/2.ttf  
    - family: My3
      fonts:
        - asset: assets/fonts/3.ttf  
    - family: My4
      fonts:
        - asset: assets/fonts/4.ttf 
    - family: My5
      fonts:
        - asset: assets/fonts/5.ttf           







       
